// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="spmv_spmv,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-1-e,HLS_INPUT_CLOCK=3.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.185000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2598,HLS_SYN_LUT=2896,HLS_VERSION=2022_2}" *)

module spmv (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rowPtr_0,
        rowPtr_1,
        rowPtr_2,
        rowPtr_3,
        rowPtr_4,
        columnIndex_address0,
        columnIndex_ce0,
        columnIndex_q0,
        values_address0,
        values_ce0,
        values_q0,
        y_address0,
        y_ce0,
        y_we0,
        y_d0,
        x_address0,
        x_ce0,
        x_q0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] rowPtr_0;
input  [31:0] rowPtr_1;
input  [31:0] rowPtr_2;
input  [31:0] rowPtr_3;
input  [31:0] rowPtr_4;
output  [3:0] columnIndex_address0;
output   columnIndex_ce0;
input  [31:0] columnIndex_q0;
output  [3:0] values_address0;
output   values_ce0;
input  [31:0] values_q0;
output  [1:0] y_address0;
output   y_ce0;
output   y_we0;
output  [31:0] y_d0;
output  [1:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_ce0;
reg y_we0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] i_1_reg_423;
wire    ap_CS_fsm_state2;
wire   [31:0] k_fu_193_p6;
reg   [31:0] k_reg_431;
wire   [0:0] icmp_ln10_fu_177_p2;
wire   [31:0] tmp_fu_204_p6;
reg   [31:0] tmp_reg_436;
wire   [2:0] grp_spmv_Pipeline_L2_fu_149_ap_return;
reg   [2:0] targetBlock_reg_441;
wire    ap_CS_fsm_state3;
wire   [31:0] empty_17_fu_279_p3;
reg   [31:0] empty_17_reg_452;
wire    ap_CS_fsm_state4;
wire   [0:0] empty_18_fu_287_p2;
reg   [0:0] empty_18_reg_457;
wire   [0:0] empty_20_fu_292_p2;
reg   [0:0] empty_20_reg_462;
wire   [0:0] empty_22_fu_297_p2;
reg   [0:0] empty_22_reg_467;
wire    grp_spmv_Pipeline_L2_fu_149_ap_start;
wire    grp_spmv_Pipeline_L2_fu_149_ap_done;
wire    grp_spmv_Pipeline_L2_fu_149_ap_idle;
wire    grp_spmv_Pipeline_L2_fu_149_ap_ready;
wire   [3:0] grp_spmv_Pipeline_L2_fu_149_values_address0;
wire    grp_spmv_Pipeline_L2_fu_149_values_ce0;
wire   [3:0] grp_spmv_Pipeline_L2_fu_149_columnIndex_address0;
wire    grp_spmv_Pipeline_L2_fu_149_columnIndex_ce0;
wire   [1:0] grp_spmv_Pipeline_L2_fu_149_x_address0;
wire    grp_spmv_Pipeline_L2_fu_149_x_ce0;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_7_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_7_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_6_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_6_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_5_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_5_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_4_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_4_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_3_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_3_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_2_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_2_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_149_y0_1_out;
wire    grp_spmv_Pipeline_L2_fu_149_y0_1_out_ap_vld;
reg    grp_spmv_Pipeline_L2_fu_149_ap_start_reg;
reg   [31:0] y0_loc_fu_102;
reg   [31:0] y0_7_loc_fu_98;
reg   [31:0] y0_6_loc_fu_94;
reg   [31:0] y0_5_loc_fu_90;
reg   [31:0] y0_4_loc_fu_86;
reg   [31:0] y0_3_loc_fu_82;
reg   [31:0] y0_2_loc_fu_78;
reg   [31:0] y0_1_loc_fu_74;
wire   [63:0] zext_ln10_fu_302_p1;
wire    ap_CS_fsm_state5;
reg   [2:0] i_fu_70;
wire   [2:0] indvars_iv_next13_fu_183_p2;
wire   [1:0] trunc_ln12_fu_189_p1;
wire   [0:0] empty_10_fu_235_p2;
wire   [0:0] empty_12_fu_248_p2;
wire   [31:0] empty_11_fu_240_p3;
wire   [0:0] empty_14_fu_261_p2;
wire   [31:0] empty_13_fu_253_p3;
wire   [0:0] empty_16_fu_274_p2;
wire   [31:0] empty_15_fu_266_p3;
wire   [31:0] empty_19_fu_315_p3;
wire   [31:0] empty_21_fu_321_p3;
wire   [31:0] y0_0_lcssa_ph_fu_328_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_spmv_Pipeline_L2_fu_149_ap_start_reg = 1'b0;
end

spmv_spmv_Pipeline_L2 grp_spmv_Pipeline_L2_fu_149(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_spmv_Pipeline_L2_fu_149_ap_start),
    .ap_done(grp_spmv_Pipeline_L2_fu_149_ap_done),
    .ap_idle(grp_spmv_Pipeline_L2_fu_149_ap_idle),
    .ap_ready(grp_spmv_Pipeline_L2_fu_149_ap_ready),
    .sext_ln12(k_reg_431),
    .sext_ln12_1(tmp_reg_436),
    .values_address0(grp_spmv_Pipeline_L2_fu_149_values_address0),
    .values_ce0(grp_spmv_Pipeline_L2_fu_149_values_ce0),
    .values_q0(values_q0),
    .columnIndex_address0(grp_spmv_Pipeline_L2_fu_149_columnIndex_address0),
    .columnIndex_ce0(grp_spmv_Pipeline_L2_fu_149_columnIndex_ce0),
    .columnIndex_q0(columnIndex_q0),
    .x_address0(grp_spmv_Pipeline_L2_fu_149_x_address0),
    .x_ce0(grp_spmv_Pipeline_L2_fu_149_x_ce0),
    .x_q0(x_q0),
    .y0_out(grp_spmv_Pipeline_L2_fu_149_y0_out),
    .y0_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_out_ap_vld),
    .y0_7_out(grp_spmv_Pipeline_L2_fu_149_y0_7_out),
    .y0_7_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_7_out_ap_vld),
    .y0_6_out(grp_spmv_Pipeline_L2_fu_149_y0_6_out),
    .y0_6_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_6_out_ap_vld),
    .y0_5_out(grp_spmv_Pipeline_L2_fu_149_y0_5_out),
    .y0_5_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_5_out_ap_vld),
    .y0_4_out(grp_spmv_Pipeline_L2_fu_149_y0_4_out),
    .y0_4_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_4_out_ap_vld),
    .y0_3_out(grp_spmv_Pipeline_L2_fu_149_y0_3_out),
    .y0_3_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_3_out_ap_vld),
    .y0_2_out(grp_spmv_Pipeline_L2_fu_149_y0_2_out),
    .y0_2_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_2_out_ap_vld),
    .y0_1_out(grp_spmv_Pipeline_L2_fu_149_y0_1_out),
    .y0_1_out_ap_vld(grp_spmv_Pipeline_L2_fu_149_y0_1_out_ap_vld),
    .ap_return(grp_spmv_Pipeline_L2_fu_149_ap_return)
);

spmv_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U18(
    .din0(rowPtr_0),
    .din1(rowPtr_1),
    .din2(rowPtr_2),
    .din3(rowPtr_3),
    .din4(trunc_ln12_fu_189_p1),
    .dout(k_fu_193_p6)
);

spmv_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U19(
    .din0(rowPtr_1),
    .din1(rowPtr_2),
    .din2(rowPtr_3),
    .din3(rowPtr_4),
    .din4(trunc_ln12_fu_189_p1),
    .dout(tmp_fu_204_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_spmv_Pipeline_L2_fu_149_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln10_fu_177_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_spmv_Pipeline_L2_fu_149_ap_start_reg <= 1'b1;
        end else if ((grp_spmv_Pipeline_L2_fu_149_ap_ready == 1'b1)) begin
            grp_spmv_Pipeline_L2_fu_149_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_70 <= 3'd0;
    end else if (((icmp_ln10_fu_177_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_70 <= indvars_iv_next13_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_17_reg_452 <= empty_17_fu_279_p3;
        empty_18_reg_457 <= empty_18_fu_287_p2;
        empty_20_reg_462 <= empty_20_fu_292_p2;
        empty_22_reg_467 <= empty_22_fu_297_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_423 <= i_fu_70;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_177_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        k_reg_431 <= k_fu_193_p6;
        tmp_reg_436 <= tmp_fu_204_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        targetBlock_reg_441 <= grp_spmv_Pipeline_L2_fu_149_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_1_out_ap_vld == 1'b1))) begin
        y0_1_loc_fu_74 <= grp_spmv_Pipeline_L2_fu_149_y0_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_2_out_ap_vld == 1'b1))) begin
        y0_2_loc_fu_78 <= grp_spmv_Pipeline_L2_fu_149_y0_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_3_out_ap_vld == 1'b1))) begin
        y0_3_loc_fu_82 <= grp_spmv_Pipeline_L2_fu_149_y0_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_4_out_ap_vld == 1'b1))) begin
        y0_4_loc_fu_86 <= grp_spmv_Pipeline_L2_fu_149_y0_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_5_out_ap_vld == 1'b1))) begin
        y0_5_loc_fu_90 <= grp_spmv_Pipeline_L2_fu_149_y0_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_6_out_ap_vld == 1'b1))) begin
        y0_6_loc_fu_94 <= grp_spmv_Pipeline_L2_fu_149_y0_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_7_out_ap_vld == 1'b1))) begin
        y0_7_loc_fu_98 <= grp_spmv_Pipeline_L2_fu_149_y0_7_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_y0_out_ap_vld == 1'b1))) begin
        y0_loc_fu_102 <= grp_spmv_Pipeline_L2_fu_149_y0_out;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_spmv_Pipeline_L2_fu_149_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln10_fu_177_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_177_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y_ce0 = 1'b1;
    end else begin
        y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y_we0 = 1'b1;
    end else begin
        y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln10_fu_177_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_spmv_Pipeline_L2_fu_149_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign columnIndex_address0 = grp_spmv_Pipeline_L2_fu_149_columnIndex_address0;

assign columnIndex_ce0 = grp_spmv_Pipeline_L2_fu_149_columnIndex_ce0;

assign empty_10_fu_235_p2 = ((targetBlock_reg_441 == 3'd0) ? 1'b1 : 1'b0);

assign empty_11_fu_240_p3 = ((empty_10_fu_235_p2[0:0] == 1'b1) ? y0_loc_fu_102 : y0_1_loc_fu_74);

assign empty_12_fu_248_p2 = ((targetBlock_reg_441 == 3'd1) ? 1'b1 : 1'b0);

assign empty_13_fu_253_p3 = ((empty_12_fu_248_p2[0:0] == 1'b1) ? y0_7_loc_fu_98 : empty_11_fu_240_p3);

assign empty_14_fu_261_p2 = ((targetBlock_reg_441 == 3'd2) ? 1'b1 : 1'b0);

assign empty_15_fu_266_p3 = ((empty_14_fu_261_p2[0:0] == 1'b1) ? y0_6_loc_fu_94 : empty_13_fu_253_p3);

assign empty_16_fu_274_p2 = ((targetBlock_reg_441 == 3'd3) ? 1'b1 : 1'b0);

assign empty_17_fu_279_p3 = ((empty_16_fu_274_p2[0:0] == 1'b1) ? y0_5_loc_fu_90 : empty_15_fu_266_p3);

assign empty_18_fu_287_p2 = ((targetBlock_reg_441 == 3'd4) ? 1'b1 : 1'b0);

assign empty_19_fu_315_p3 = ((empty_18_reg_457[0:0] == 1'b1) ? y0_4_loc_fu_86 : empty_17_reg_452);

assign empty_20_fu_292_p2 = ((targetBlock_reg_441 == 3'd5) ? 1'b1 : 1'b0);

assign empty_21_fu_321_p3 = ((empty_20_reg_462[0:0] == 1'b1) ? y0_3_loc_fu_82 : empty_19_fu_315_p3);

assign empty_22_fu_297_p2 = ((targetBlock_reg_441 == 3'd6) ? 1'b1 : 1'b0);

assign grp_spmv_Pipeline_L2_fu_149_ap_start = grp_spmv_Pipeline_L2_fu_149_ap_start_reg;

assign icmp_ln10_fu_177_p2 = ((i_fu_70 == 3'd4) ? 1'b1 : 1'b0);

assign indvars_iv_next13_fu_183_p2 = (i_fu_70 + 3'd1);

assign trunc_ln12_fu_189_p1 = i_fu_70[1:0];

assign values_address0 = grp_spmv_Pipeline_L2_fu_149_values_address0;

assign values_ce0 = grp_spmv_Pipeline_L2_fu_149_values_ce0;

assign x_address0 = grp_spmv_Pipeline_L2_fu_149_x_address0;

assign x_ce0 = grp_spmv_Pipeline_L2_fu_149_x_ce0;

assign y0_0_lcssa_ph_fu_328_p3 = ((empty_22_reg_467[0:0] == 1'b1) ? y0_2_loc_fu_78 : empty_21_fu_321_p3);

assign y_address0 = zext_ln10_fu_302_p1;

assign y_d0 = y0_0_lcssa_ph_fu_328_p3;

assign zext_ln10_fu_302_p1 = i_1_reg_423;

endmodule //spmv
